# REQUEST
GET /api/v1/products

# RESPONSE
[
  {
    "id": "4ca4eb7f-5545-4982-ad38-743dab52e31d",
    "name": "Zomo de Morango",
    "tags": ["zomo", "essencia", "morango"]
  },
  {
    "id": "d1d5a14f-57d2-4613-80c8-fa4f78fff171",
    "name": "Carvao",
    "tags": ["carvao"]
  },
  {
    "id": "5a48358b-e88f-4434-a210-6d6fb389f777",
    "name": "Aluminio",
    "tags": ["aluminio"]
  }
]

