# REQUEST
GET /api/v1/sales/catalog/billables

# RESPONSE
{
  "page": 1
  "data": [
    {
      "id": "68faa9a9-bfbb-4c31-8240-b657a27d9dde",
      "name": "Zomo de Morango",
      "products": ["4ca4eb7f-5545-4982-ad38-743dab52e31d"],
      "amount": "15.00"
    },
    {
      "id": "dc93515d-048e-4181-a437-f83d970de863",
      "name": "Carvao",
      "products": ["d1d5a14f-57d2-4613-80c8-fa4f78fff171"],
      "amount": "1.50"
    },
    {
      "id": "35d4632c-dd5c-486c-979a-d034feeed496",
      "name": "Aluminio",
      "products": ["5a48358b-e88f-4434-a210-6d6fb389f777"],
      "amount": "2.00"
    },
    {
      "id": "bf947a5f-29e0-47d4-8633-f9c365ced1fb",
      "name": "Essencia Zomo de Morango, Carvao e aluminio",
      "products": [
        "4ca4eb7f-5545-4982-ad38-743dab52e31d",
        "d1d5a14f-57d2-4613-80c8-fa4f78fff171",
        "5a48358b-e88f-4434-a210-6d6fb389f777"
      ],
      "amount": "20.00"
    }
  ]
}
