# REQUEST
POST /api/v1/sales/catalog/billables

# BODY
{
  "name": "Zomo de Morango",
  "products": ["4ca4eb7f-5545-4982-ad38-743dab52e31d"],
  "amount": "15.00"
}
or
{
  "name": "Essencia Zomo de Morango, Carvao e aluminio",
  "products": [
    "4ca4eb7f-5545-4982-ad38-743dab52e31d",
    "d1d5a14f-57d2-4613-80c8-fa4f78fff171",
    "5a48358b-e88f-4434-a210-6d6fb389f777"
  ],
  "amount": "20.00"
}

