# REQUEST
POST /api/v1/shopping

# BODY
{
  products: [
    {
      "id": "e901425f-49e7-433e-a8f3-c2395800fdc1",
      "quantity": "10",
      "amount": "50.00"
    },
    {
      "id": "3ec37097-3b27-4b6f-ab10-35e6492c99d3",
      "quantity": "21",
      "amount": "150.00"
    },
  ]
}
